### PR TITLE
feat: Add support for Helia.

### PR DESCRIPTION
**Pull request by saul-jb**
After the release of [Helia](https://github.com/ipfs/helia), [maintenance for js-ipfs is stopping](https://blog.ipfs.tech/state-of-ipfs-in-js/#pause-js-ipfs-maintenance-once-helia-is-released) so this PR adds support for Helia alongside the original `ipfs-core` interface.

This is done by using the underlying `libp2p` API where possible (since both `ipfs-core` and `helia` expose it) and checking which of the `blockstore`  or `block` properties are exposed.

This PR also refactors the tests to use the more lighter weight `helia` package instead of `ipfs-core`.

### CODE REVIEW

**Comment by saul-jb** [comment]
Helia requires a persistent block storage in order to work with OrbitDB, the default memory will not work unless the LevelStorage that stores the heads is cleared first, otherwise Helia looks for a block that is no longer there. An alternative way to fix this is remove the persistent storage of the heads created [here](https://github.com/orbitdb/orbit-db-nextgen/blob/main/src/database.js#L24).

I will also note this problem does not occur if the access control settings is set to something new.

Although this causes problems with Helia when using the default memory block store, it is not a problem with this fork per se since the same problem will happen with ipfs-core in the current implementation if the IPFS storage does not persist or is cleared.

This fork should be complete and functional but someone will need to take a look and figure out how to handle the situation if the blocks to the heads no longer exist.

**Comment by justin0mcateer** [comment]
Is there anything I could help with here, or is this purely awaiting maintainer review?

**Comment by saul-jb** [comment]
> Is there anything I could help with here, or is this purely awaiting maintainer review?

Yeah, just waiting for the maintainers to have a look, they did tell me that they wanted time to look into Helia and it would be some time before they got to it.

I have been using it for a while and it does seem to work pretty good (other than the potential issue I describe in my last comment) but I should update this fork.

**Comment by spryzone** [comment]
Looking forward to Helia integration with orbit-db-nextgen

**Comment by andrewzhurov** [comment]
Thanks for the effort, @saul-jb! Would love to see OrbitDB migrating over to Helia. That would rock!
Let me know if I may be of help to get it closer to completion, I can dedicate a couple of weeks to that

**Comment by nicocossiom** [comment]
This is quite amazing. Tbh I don't really like js-ipfs and Helia seems like a much better ipfs implementation. I want to migrate the application I am writing for my degree thesis to Helia but since I use OrbitDB as an integral part of my application I am kind of waiting on this.
I have some questions regarding this fork: will this be a new separate orbitdb package for helia? or is this just a new fork to work on features to keep Orbitdb updated to the latest and when ready merged upstream ?
Another question, regarding when do you think this might be ready? I am somewhat on a schedule for the delivery of my thesis, hence it would be very much appreciated if there was any ETA on when we can expect this integrated upstream. No pressure sine I don't think that I will have time. 

Thank you in advanced for this, I think it will be a huge step towards making OrbitDB more accesible and used with the upcoming of Helia.

**Comment by saul-jb** [comment]
>  Tbh I don't really like js-ipfs and Helia seems like a much better ipfs implementation.

I think a lot of us think this way.

> I want to migrate the application I am writing for my degree thesis to Helia but since I use OrbitDB as an integral part of my application I am kind of waiting on this.

I made this changes to be backwards compatible so if the rest of your application works with both Helia and OrbitDB is should be trivial to change over. That being said I do not know if the owners would change this or not. What you could do in the meantime is wrap Helia in something that looks like js-ipfs (at least the small part of the API that actually gets used) and use it in place of it, if you really want to change over soon.

> will this be a new separate orbitdb package for helia? or is this just a new fork to work on features to keep Orbitdb updated to the latest and when ready merged upstream ?

Last I talked to Haad it sounded as if it would get merged at some point but it was further down the priority list. I haven't been too worried about keeping it up to date until there is indication they are ready to merge it.

> when do you think this might be ready?

I don't know myself but perhaps @haadcode could comment?

**Comment by andrewzhurov** [comment]
In orbit-db-nextgen adding events to a log is blazing fast at the beginning and starts to slow down rapidly, is this something that can be improved?

record

In the example above,
Events are strings "[:inc-counter]" (serialized EDN)
1k of these events been issued as eventdb.add("[:inc-counter]")
I turned on performance profiled (screenshot below) (that is when events stopped being processed for a couple of seconds in the gif above)

https://share.firefox.dev/3r0J2rH (this is the profile of another test run, on events from ~100 to ~125)
image

**Comment by justin0mcateer** [comment]
Have you run the same test on the current 'orbit-db' main to see if the performance has regressed? Just from reviewing the code, I know there are several instances where it reads and sort the entire log (in the current 'main' version). Your profile data makes it look like that might be part of the problem here.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrewzhurov** [comment]
Ran it on [orbit-db v 0.29.0](https://github.com/orbitdb/orbit-db/commit/a7cea49) (latest as of now)
It's not the exact same test though, configuration is slightly different
record
https://share.firefox.dev/3qY0JYI
image

----

And here's the run without GUI updates

https://github.com/orbitdb/orbit-db-nextgen/assets/13056889/ab01635f-f468-4ceb-94fd-8dd58cb6206b

https://share.firefox.dev/43MI2pr
image

**Comment by andrewzhurov** [comment]
I'm experiencing an interesting scenario, where two browser nodes A and B open the same database, node B adds a bunch of events to it, then they connect and exchange heads, node A receives only the head of that bunch of events, so only the last event made by node B gets propagated to it, the others do not. Is this intended? I'd expect all the events being propagated


https://github.com/orbitdb/orbit-db-nextgen/assets/13056889/a5567f7f-1e8b-497b-b3ca-564962f94190

**Comment by haydenyoung** [comment]
> I'm experiencing an interesting scenario, where two browser nodes A and B open the same database, node B adds a bunch of events to it, then they connect and exchange heads, node A receives only the head of that bunch of events, so only the last event made by node B gets propagated to it, the others do not. Is this intended? I'd expect all the events being propagated
> record.mp4

You're correct, only the heads are replicated. To complete the replication process, you explicitly iterate over the recordset which will replicate all records. See https://github.com/orbitdb/orbit-db-nextgen/blob/main/docs/DATABASES.md#replicating-a-database-across-peers for an example.

**Comment by andrewzhurov** [comment]
Fetching entries ad-hoc, when needed, from the underlying IPFSBlockStore - damm, I love how elegant that is, thanks for the pointer!

**Comment by andrewzhurov** [comment]
Can it be that .iterator with `lt` or `lte` will not return entities that been added to log in parallel?
On example
```
AB1 <- A2 <- A3
  ^--- B2 <- B3
```
where AB1 is a commonly known entry by both peer A and peer B, and A2, A3, B2, B3 - novel entries, added by peers in parallel.

Then, when they sync up and try to iterate with `lt` or `lte` pointing to a novel entry (say A3), will iterator skip entries that's been added in parallel?
```
.iterator({lt: A3}) => [A2, AB1]
.iterator({lt: B3}) => [B2, AB1]
```
As [it takes `nexts` from the supplied `lt` or `lte`](https://github.com/saul-jb/orbit-db-nextgen/blob/7fad8cfad5f7b00d72839dc48831aa39f475c60d/src/oplog/log.js#L393) and they don't contain entries that's been added in parallel (so A3 doesn't contain B2).
If so, is it intended?

Perhaps it is my out-of-design use-case where I'd like to get all entries `lt` than say A3, returning [A2, B2, AB1]
```
.iterator({lt: A3}) => [A2, B2, AB1]
```

**Comment by justin0mcateer** [comment]
This PR dropped the timeouts for `IPFSBlockStorage.get()` and `IPFSBlockStorage.put()`.

These can be added with a simple call to 'AbortSignal.timeout' as shown below:
```javascript
const block = ipfs.blockstore ? await ipfs.blockstore.get(cid, { signal: AbortSignal.timeout(timeout) }) : await ipfs.block.get(cid, { timeout })
```

**Comment by SgtPooki** [comment]
Hey there,

Helia maintainer here, just checking in to see if there's anything you need from us in Helia that would make use of it easier. 

Also, please feel free to open any issues regarding bugs/feature requests at github.com/ipfs/helia or discussions at https://discuss.ipfs.tech/c/help/helia/40

**Comment by devtestingstuff** [comment]
Are there any updates here?

**Comment by saul-jb** [comment]
> Are there any updates here?

By the sounds of things this fork has fallen to far behind and they are not prioritizing Helia. I think a new fork would need to be done.

**Comment by haadcode** [comment]
Thanks everyone for following up on this. As the code from this repo has been merged to [main orbitdb repo](https://github.com/orbitdb/orbitdb), this repo is indeed inactive. That however doesn't mean Helia is not a priority, rather it's been moved to [helia branch](https://github.com/orbitdb/orbitdb/tree/helia) in the main repo and it's actively been worked on.

Closing this PR but contributions are welcome in the main repo!

**Pull request closed without merging**
